In [11]:
import numpy as np

import numpy as np


# Define the file paths
train_data_path = 'data/train_data.txt'
test_data_path = 'data/test_data.txt'

train_label_path = 'data/train_labels.txt'
test_label_path = 'data/test_labels.txt'

# Load the data from the text files into NumPy arrays, handling 'nan' values
train_data = np.genfromtxt(train_data_path, delimiter=',', skip_header=0, dtype=float, filling_values=np.nan)
test_data = np.genfromtxt(test_data_path, delimiter=',', skip_header=0, dtype=float, filling_values=np.nan)

# Load the labels from the text files into NumPy arrays
train_labels = np.genfromtxt(train_label_path, delimiter=',', skip_header=0, dtype=float, filling_values=np.nan)
test_labels = np.genfromtxt(test_label_path, delimiter=',', skip_header=0, dtype=float, filling_values=np.nan)

# Combine the train and test data
combined_data = np.vstack((train_data, test_data))

# Combine the train and test labels
combined_labels = np.hstack((train_labels, test_labels))

# Save the combined data and labels to .npy files
np.save('data/rbf_feature.npy', combined_data)
np.save('data/rbf_labels.npy', combined_labels)

In [64]:
dataname = [
# "data/breast_cancer/", #cat
# "data/car_evaluation/", #cat
#"data/climate_model_crashes/",
#"data/concrete_compression/", # reg
# "data/solar_fire/",#cat
#"data/wine_quality_white/", #reg
"data/qsar_biodegradation/",
"data/connectionist_bench_sonar/",
"data/yeast/",
#"data/yacht_hydrodynamics/" # reg
]

for data in dataname:

    combined_data = np.load(f'{data}feature.npy',allow_pickle=True)
    combined_labels = np.load(f'{data}label.npy',allow_pickle=True)

    print(data)

    print(set(combined_labels))


data/qsar_biodegradation/
{0, 1}
data/connectionist_bench_sonar/
{0, 1}
data/yeast/
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [48]:
from ucimlrepo import fetch_ucirepo 
  


Attribute1  Attribute2  Attribute3  Attribute4  Attribute5  Attribute6  \
0        0.0200      0.0371      0.0428      0.0207      0.0954      0.0986   
1        0.0453      0.0523      0.0843      0.0689      0.1183      0.2583   
2        0.0262      0.0582      0.1099      0.1083      0.0974      0.2280   
3        0.0100      0.0171      0.0623      0.0205      0.0205      0.0368   
4        0.0762      0.0666      0.0481      0.0394      0.0590      0.0649   
..          ...         ...         ...         ...         ...         ...   
203      0.0187      0.0346      0.0168      0.0177      0.0393      0.1630   
204      0.0323      0.0101      0.0298      0.0564      0.0760      0.0958   
205      0.0522      0.0437      0.0180      0.0292      0.0351      0.1171   
206      0.0303      0.0353      0.0490      0.0608      0.0167      0.1354   
207      0.0260      0.0363      0.0136      0.0272      0.0214      0.0338   

     Attribute7  Attribute8  Attribute9  Attribute10  ...  Attribute51  \
0        0.1539      0.1601      0.3109       0.2111  ...       0.0232   
1        0.2156      0.3481      0.3337       0.2872  ...       0.0125   
2        0.2431      0.3771      0.5598       0.6194  ...       0.0033   
3        0.1098      0.1276      0.0598       0.1264  ...       0.0241   
4        0.1209      0.2467      0.3564       0.4459  ...       0.0156   
..          ...         ...         ...          ...  ...          ...   
203      0.2028      0.1694      0.2328       0.2684  ...       0.0203   
204      0.0990      0.1018      0.1030       0.2154  ...       0.0051   
205      0.1257      0.1178      0.1258       0.2529  ...       0.0155   
206      0.1465      0.1123      0.1945       0.2354  ...       0.0042   
207      0.0655      0.1400      0.1843       0.2354  ...       0.0181   

     Attribute52  Attribute53  Attribute54  Attribute55  Attribute56  \
0         0.0027       0.0065       0.0159       0.0072       0.0167   
1         0.0084       0.0089       0.0048       0.0094       0.0191   
2         0.0232       0.0166       0.0095       0.0180       0.0244   
3         0.0121       0.0036       0.0150       0.0085       0.0073   
4         0.0031       0.0054       0.0105       0.0110       0.0015   
..           ...          ...          ...          ...          ...   
203       0.0116       0.0098       0.0199       0.0033       0.0101   
204       0.0061       0.0093       0.0135       0.0063       0.0063   
205       0.0160       0.0029       0.0051       0.0062       0.0089   
206       0.0086       0.0046       0.0126       0.0036       0.0035   
207       0.0146       0.0129       0.0047       0.0039       0.0061   

     Attribute57  Attribute58  Attribute59  Attribute60  
0         0.0180       0.0084       0.0090       0.0032  
1         0.0140       0.0049       0.0052       0.0044  
2         0.0316       0.0164       0.0095       0.0078  
3         0.0050       0.0044       0.0040       0.0117  
4         0.0072       0.0048       0.0107       0.0094  
..           ...          ...          ...          ...  
203       0.0065       0.0115       0.0193       0.0157  
204       0.0034       0.0032       0.0062       0.0067  
205       0.0140       0.0138       0.0077       0.0031  
206       0.0034       0.0079       0.0036       0.0048  
207       0.0040       0.0036       0.0061       0.0115  

[208 rows x 60 columns]

In [55]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [63]:
# fetch dataset 
connectionist_bench_sonar_mines_vs_rocks = fetch_ucirepo(id=151) 

# data (as pandas dataframes) 
features = connectionist_bench_sonar_mines_vs_rocks.data.features 
labels = connectionist_bench_sonar_mines_vs_rocks.data.targets

label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

features = np.array(features)
labels = np.array(encoded_labels)

print(features)
print(labels)

# Save the features and labels to separate .npy files
np.save('data/connectionist_bench_sonar/feature.npy', features)
np.save('data/connectionist_bench_sonar/label.npy', labels)

[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


/Users/epochoid/opt/anaconda3/envs/mass/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [62]:
# fetch dataset 
qsar_biodegradation = pd.read_csv("data/qsar_biodegradation/qsar_biodegradation.csv",sep=";")


# Assume the labels are in the last column and features are all other columns
features = qsar_biodegradation.iloc[:, :-1]
labels = qsar_biodegradation.iloc[:, -1]

#Apply label encoding to the labels
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Convert features and labels to NumPy arrays
features = np.array(features)
labels = np.array(encoded_labels)

# Print the features and labels to verify
print("Features:")
print(features)
print("Labels:")
print(labels)

# Save the features and labels to separate .npy files
np.save('data/qsar_biodegradation/feature.npy', features)
np.save('data/qsar_biodegradation/label.npy', labels)


Features:
[[ 4.17    2.1144  0.     ...  7.257   0.      0.    ]
 [ 3.932   3.2512  0.     ...  7.601   0.      0.    ]
 [ 3.      2.7098  0.     ...  6.69    0.      0.    ]
 ...
 [ 4.869   1.767   0.     ...  9.537   1.      0.    ]
 [ 5.158   1.6914  2.     ... 11.055   0.      1.    ]
 [ 5.076   2.6588  2.     ...  9.13    0.      2.    ]]
Labels:
[1 1 1 ... 0 0 0]


In [51]:
labels

array([['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
       ['R'],
      

In [12]:
# Calculate missing rates
total_elements = combined_data.size
missing_elements = np.isnan(combined_data).sum()
overall_missing_rate = missing_elements / total_elements

column_missing_rate = np.isnan(combined_data).sum(axis=0) / combined_data.shape[0]

# Print missing rates
print(f"Overall missing rate: {overall_missing_rate:.2%}")
print("Column-wise missing rates:")
for i, rate in enumerate(column_missing_rate):
    print(f"Column {i}: {rate:.2%}")

Overall missing rate: 19.37%
Column-wise missing rates:
Column 0: 20.46%
Column 1: 20.77%
Column 2: 36.23%
Column 3: 0.00%
